export const BG_COLOR: string = "#A2B6AB";
export const M_COLOR: string = "#030906";
export const SM_COLOR: string = "#8F9E99";
export const SECOND: number = 1000;
export const GAME_TABLE_X: number = 10;
export const GAME_TABLE_Y: number = 20;
export const CAR_W = 3;
export const CAR_H = 4;
export const FPS = 60;